/* ============================================================
   typo — text corpus
   Quotes are grouped by length. Quote bodies are kept strictly
   to ASCII so every character is reachable from a standard
   keyboard; accents may only appear inside the attribution,
   which is never typed.
   ============================================================ */

window.QUOTES = {

  short: [
    { text: "Readability counts.", from: "Tim Peters, The Zen of Python" },
    { text: "Less is more.", from: "Ludwig Mies van der Rohe" },
    { text: "Less, but better.", from: "Dieter Rams" },
    { text: "Call me Ishmael.", from: "Herman Melville, Moby-Dick" },
    { text: "I think, therefore I am.", from: "René Descartes" },
    { text: "Talk is cheap. Show me the code.", from: "Linus Torvalds" },
    { text: "Now is better than never.", from: "Tim Peters, The Zen of Python" },
    { text: "Deleted code is debugged code.", from: "Jeff Sickel" },
    { text: "Stay hungry, stay foolish.", from: "Steve Jobs, Stanford, 2005" },
    { text: "Design is thinking made visual.", from: "Saul Bass" },
    { text: "Good design is unobtrusive.", from: "Dieter Rams" },
    { text: "Good design is as little design as possible.", from: "Dieter Rams" },
    { text: "Simple is better than complex.", from: "Tim Peters, The Zen of Python" },
    { text: "Well done is better than well said.", from: "Benjamin Franklin" },
    { text: "Premature optimization is the root of all evil.", from: "Donald Knuth" },
    { text: "Simplicity is prerequisite for reliability.", from: "Edsger W. Dijkstra" },
    { text: "The unexamined life is not worth living.", from: "Socrates" },
    { text: "The computer is a bicycle for the mind.", from: "Steve Jobs, 1980" },
    { text: "Make it work, make it right, make it fast.", from: "Kent Beck" },
    { text: "Simplicity carried to an extreme becomes elegance.", from: "Jon Franklin" },
    { text: "The truth is rarely pure and never simple.", from: "Oscar Wilde" },
    { text: "An investment in knowledge pays the best interest.", from: "Benjamin Franklin" },
    { text: "First, solve the problem. Then, write the code.", from: "John Johnson" },
    { text: "It is not down on any map; true places never are.", from: "Herman Melville" },
    { text: "Truth can only be found in one place: the code.", from: "Robert C. Martin" },
    { text: "The best way to predict the future is to invent it.", from: "Alan Kay" },
    { text: "It was the best of times, it was the worst of times.", from: "Charles Dickens" },
    { text: "Experience is the name everyone gives to their mistakes.", from: "Oscar Wilde" },
    { text: "The details are not the details. They make the design.", from: "Charles Eames" },
    { text: "Optimization hinders evolution.", from: "Alan Perlis, Epigrams in Programming" },
    { text: "Within a computer, natural language is unnatural.", from: "Alan Perlis" },
    { text: "Simplicity does not precede complexity, but follows it.", from: "Alan Perlis" },
    { text: "Everything is designed. Few things are designed well.", from: "Brian Reed" },
    { text: "The only way to do great work is to love what you do.", from: "Steve Jobs" },
    { text: "Imagination is more important than knowledge.", from: "Albert Einstein" },
    { text: "The important thing is not to stop questioning.", from: "Albert Einstein" },
    { text: "I have no special talents. I am only passionately curious.", from: "Albert Einstein" },
    { text: "Strive not to be a success, but rather to be of value.", from: "Albert Einstein" },
    { text: "Anyone who has never made a mistake has never tried anything new.", from: "Albert Einstein" },
    { text: "Not all those who wander are lost.", from: "J. R. R. Tolkien" },
    { text: "It does not do to dwell on dreams and forget to live.", from: "J. K. Rowling" },
    { text: "The only thing we have to fear is fear itself.", from: "Franklin D. Roosevelt, 1933" },
    { text: "The greatest of faults, I should say, is to be conscious of none.", from: "Thomas Carlyle" }
  ],

  medium: [
    { text: "Any sufficiently advanced technology is indistinguishable from magic.", from: "Arthur C. Clarke" },
    { text: "Controlling complexity is the essence of computer programming.", from: "Brian Kernighan" },
    { text: "Code is like humor. When you have to explain it, it is bad.", from: "Cory House" },
    { text: "One man's crappy software is another man's full time job.", from: "Jessica Gaston" },
    { text: "Everyone knows debugging is twice as hard as writing a program.", from: "Brian Kernighan" },
    { text: "We are all in the gutter, but some of us are looking at the stars.", from: "Oscar Wilde" },
    { text: "There are only two hard things in computer science: cache invalidation and naming things.", from: "Phil Karlton" },
    { text: "The sky above the port was the color of television, tuned to a dead channel.", from: "William Gibson, Neuromancer" },
    { text: "So we beat on, boats against the current, borne back ceaselessly into the past.", from: "F. Scott Fitzgerald" },
    { text: "Have nothing in your house that you do not know to be useful, or believe to be beautiful.", from: "William Morris" },
    { text: "Either write something worth reading or do something worth writing.", from: "Benjamin Franklin" },
    { text: "Programs must be written for people to read, and only incidentally for machines to execute.", from: "Abelson and Sussman, SICP" },
    { text: "Design is not just what it looks like and feels like. Design is how it works.", from: "Steve Jobs" },
    { text: "All happy families are alike; each unhappy family is unhappy in its own way.", from: "Leo Tolstoy, Anna Karenina" },
    { text: "The first principle is that you must not fool yourself and you are the easiest person to fool.", from: "Richard Feynman" },
    { text: "We can only see a short distance ahead, but we can see plenty there that needs to be done.", from: "Alan Turing" },
    { text: "A computer would deserve to be called intelligent if it could deceive a human into believing that it was human.", from: "Alan Turing" },
    { text: "A language that does not affect the way you think about programming is not worth knowing.", from: "Alan Perlis" },
    { text: "If you have a procedure with ten parameters, you probably missed some.", from: "Alan Perlis" },
    { text: "It is easier to write an incorrect program than understand a correct one.", from: "Alan Perlis" },
    { text: "The world breaks everyone, and afterward many are strong at the broken places.", from: "Ernest Hemingway" },
    { text: "All we have to decide is what to do with the time that is given us.", from: "J. R. R. Tolkien" },
    { text: "Strange women lying in ponds distributing swords is no basis for a system of government.", from: "Monty Python and the Holy Grail" },
    { text: "A designer knows he has achieved perfection not when there is nothing left to add.", from: "Antoine de Saint-Exupéry" },
    { text: "Simple things should be simple, complex things should be possible.", from: "Alan Kay" },
    { text: "The most disastrous thing you can ever learn is your first programming language.", from: "Alan Kay" }
  ],

  long: [
    { text: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", from: "Jane Austen, Pride and Prejudice" },
    { text: "The reasonable man adapts himself to the world: the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man.", from: "George Bernard Shaw" },
    { text: "When you have mastered numbers, you will in fact no longer be reading numbers, any more than you read words when reading books. You will be reading meanings.", from: "W. E. B. Du Bois" },
    { text: "Perfection is finally attained not when there is no longer anything to add, but when there is no longer anything to take away.", from: "Antoine de Saint-Exupéry, Terre des Hommes" },
    { text: "A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.", from: "Douglas Adams" },
    { text: "The whole point of the UNIX philosophy is that the system should be simple enough that a competent programmer can hold the entire design in their head at once.", from: "Rob Pike" },
    { text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", from: "Martin Fowler" },
    { text: "There are two ways of constructing a software design: one way is to make it so simple that there are obviously no deficiencies.", from: "C. A. R. Hoare" },
    { text: "Nothing is more fairly distributed than common sense: no one thinks he needs more of it than he already has.", from: "René Descartes" },
    { text: "Everybody is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid.", from: "Albert Einstein" },
    { text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.", from: "Albert Einstein" },
    { text: "Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning.", from: "Albert Einstein" },
    { text: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.", from: "Marie Curie" },
    { text: "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.", from: "Roy T. Bennett" },
    { text: "Do not judge me by my successes, judge me by how many times I fell down and got back up again.", from: "Nelson Mandela" },
    { text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", from: "Mark Twain" },
    { text: "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure.", from: "Marianne Williamson" },
    { text: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", from: "Carl Jung" },
    { text: "Have the courage to follow your heart and intuition. They somehow already know what you truly want to become.", from: "Steve Jobs" },
    { text: "Being the richest man in the cemetery doesn't matter to me. Going to bed at night saying we've done something wonderful, that's what matters to me.", from: "Steve Jobs" },
    { text: "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.", from: "Leonardo da Vinci" },
    { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", from: "Marcus Aurelius, Meditations" }
  ]

};

window.WORDS = [
  "about", "above", "across", "action", "after", "again", "against", "almost",
  "alone", "along", "already", "although", "always", "among", "amount", "another",
  "answer", "appear", "around", "arrive", "become", "before", "begin", "behind",
  "believe", "better", "between", "beyond", "bring", "build", "business", "camera",
  "cancel", "carry", "catch", "center", "certain", "change", "choose", "circle",
  "claim", "class", "clear", "close", "common", "company", "compare", "complete",
  "computer", "concern", "condition", "consider", "contain", "continue", "control",
  "corner", "country", "course", "create", "current", "danger", "decide", "degree",
  "deliver", "demand", "describe", "design", "detail", "develop", "difference",
  "difficult", "direct", "discover", "discuss", "distance", "divide", "double",
  "doubt", "during", "early", "easily", "economy", "either", "element", "energy",
  "enough", "enter", "entire", "environment", "escape", "evening", "event", "every",
  "exactly", "example", "expect", "experience", "explain", "express", "extend",
  "family", "famous", "father", "feature", "figure", "final", "finger", "finish",
  "follow", "foreign", "forget", "forward", "freedom", "friend", "future", "garden",
  "gather", "general", "gentle", "govern", "ground", "group", "growth", "happen",
  "health", "history", "honor", "however", "human", "hundred", "husband", "imagine",
  "improve", "include", "increase", "indeed", "industry", "inside", "instead",
  "interest", "issue", "itself", "journey", "judge", "kitchen", "knowledge",
  "language", "later", "laugh", "leader", "learn", "leave", "length", "letter",
  "level", "light", "listen", "little", "machine", "magazine", "maintain", "manage",
  "market", "master", "material", "matter", "maybe", "measure", "medical", "member",
  "message", "method", "middle", "might", "minute", "mirror", "modern", "moment",
  "money", "month", "morning", "mother", "mountain", "movement", "music", "national",
  "nature", "near", "necessary", "neither", "never", "night", "noise", "north",
  "nothing", "notice", "number", "object", "observe", "obtain", "occur", "offer",
  "office", "often", "order", "ordinary", "organize", "original", "outside", "paint",
  "paper", "parent", "particular", "party", "patient", "pattern", "people", "perfect",
  "perhaps", "period", "person", "picture", "place", "plan", "plant", "play",
  "please", "point", "police", "political", "possible", "power", "practice",
  "prepare", "present", "president", "pressure", "pretty", "prevent", "price",
  "print", "private", "probably", "problem", "process", "produce", "product",
  "program", "project", "proper", "protect", "prove", "provide", "public", "purpose",
  "quality", "question", "quickly", "quiet", "radio", "raise", "rather", "reach",
  "ready", "reason", "receive", "recent", "record", "reduce", "reflect", "region",
  "relate", "remain", "remember", "remove", "repeat", "report", "request", "require",
  "research", "resource", "respond", "result", "return", "reveal", "review", "right",
  "river", "round", "safety", "satisfy", "school", "science", "screen", "search",
  "season", "second", "secret", "section", "security", "sense", "sentence",
  "separate", "serious", "service", "several", "shadow", "should", "shoulder",
  "signal", "similar", "simple", "single", "sister", "situation", "skill", "sleep",
  "small", "smile", "social", "society", "soldier", "solution", "someone",
  "something", "sometimes", "sound", "source", "south", "space", "speak", "special",
  "spend", "spread", "spring", "staff", "stage", "stand", "standard", "start",
  "state", "station", "stay", "step", "still", "story", "straight", "strange",
  "street", "strength", "strong", "structure", "student", "study", "style",
  "subject", "success", "sudden", "suggest", "summer", "support", "suppose",
  "surface", "surprise", "system", "table", "teach", "teacher", "theory", "though",
  "thought", "thousand", "through", "together", "tomorrow", "tonight", "toward",
  "travel", "trouble", "truth", "understand", "universe", "until", "usual", "value",
  "various", "village", "visit", "voice", "volume", "wait", "walk", "warm", "watch",
  "water", "weather", "week", "weight", "welcome", "whether", "which", "while",
  "whole", "window", "winter", "within", "without", "woman", "wonder", "world",
  "worry", "worth", "write", "writer", "wrong", "yellow", "young"
];
